# 4. Handling Errors

What will the output be for the following code?

var p = new Promise((resolve, reject) => {
    reject(Error('The Fails!'))
  })
  .catch(error => console.log(error.message))
  .catch(error => console.log(error.message))
------

1. print error message once
2. print error message twice
3. UnhandledPromiseRejectionWarning
4. process exits

[credit](https://danlevy.net/)
